/**
 * Twitch Auth Module
 * Implicit-grant ("token") OAuth login against Twitch for the scene creator, so a
 * signed-in user can be identified against the proxy's account routes without a
 * server-side client secret. Twitch returns the token in the URL *hash* on
 * success and in the *query string* on failure — see handleRedirect().
 *
 * All storage access is wrapped in try/catch: this module must never throw,
 * even in private browsing / storage-denied contexts.
 */

import { UIHelpers } from './ui-helpers.js';

export const TWITCH_CLIENT_ID = 'k7in1vseqo21o7cxbpocozdzaz2wme';

// localStorage: { accessToken, obtainedAt(ms), expiresAt(ms|null) }
export const AUTH_KEY = 'twitchAuth';
// localStorage: { id, login, displayName, avatarUrl, cachedAt(ms) }
export const USER_KEY = 'twitchAuthUser';
// sessionStorage: the CSRF state string generated by login()
export const STATE_KEY = 'twitchAuthState';

export const AUTHORIZE_URL = 'https://id.twitch.tv/oauth2/authorize';
export const VALIDATE_URL = 'https://id.twitch.tv/oauth2/validate';
export const REVOKE_URL = 'https://id.twitch.tv/oauth2/revoke';
export const USERS_URL = 'https://api.twitch.tv/helix/users';

/**
 * The redirect_uri Twitch sends the user back to. Deliberately drops any
 * query/hash so it matches exactly what's registered with Twitch and so the
 * redirect always lands somewhere handleRedirect() can clean up.
 */
export function getRedirectUri() {
    return window.location.origin + window.location.pathname;
}

/**
 * Kick off the Twitch implicit-grant flow. Stores a CSRF `state` value in
 * sessionStorage (checked by handleRedirect()) and navigates to Twitch's
 * authorize screen.
 */
export function login({ navigate = (url) => window.location.assign(url) } = {}) {
    const state = UIHelpers.generateUUID();
    try {
        sessionStorage.setItem(STATE_KEY, state);
    } catch (e) {
        // sessionStorage unavailable — state_mismatch will fire on return, which
        // surfaces as a normal "try again" error rather than a silent failure.
    }

    const params = new URLSearchParams({
        response_type: 'token',
        client_id: TWITCH_CLIENT_ID,
        redirect_uri: getRedirectUri(),
        scope: '', // Must be present (even empty) — Twitch 400s a missing scope param.
        state,
        force_verify: 'false'
    });

    navigate(`${AUTHORIZE_URL}?${params.toString()}`);
}

/**
 * Parse a Twitch OAuth redirect. Success lands in the URL hash
 * (#access_token=...&scope=&state=...&token_type=bearer); failure lands in the
 * query string (?error=access_denied&error_description=...&state=...).
 *
 * Always cleans the URL (strips error/error_description/state, drops the hash)
 * on any non-'none' result so a reload doesn't replay the redirect.
 *
 * @returns {{status: 'none'|'ok'|'error'|'state_mismatch', message?: string}}
 */
export function handleRedirect({ loc = window.location, hist = window.history } = {}) {
    const hashStr = (loc.hash || '').startsWith('#') ? loc.hash.slice(1) : (loc.hash || '');
    const hashParams = new URLSearchParams(hashStr);
    const searchParams = new URLSearchParams(loc.search || '');

    const accessToken = hashParams.get('access_token');
    const error = searchParams.get('error');

    if (!accessToken && !error) {
        return { status: 'none' };
    }

    let expectedState = null;
    try {
        expectedState = sessionStorage.getItem(STATE_KEY);
        sessionStorage.removeItem(STATE_KEY);
    } catch (e) {
        // Fall through with expectedState = null; a present state will then
        // (correctly) fail to match and surface as state_mismatch.
    }

    let result;
    if (accessToken) {
        const state = hashParams.get('state');
        // Both sides must be present: with no login in flight expectedState is
        // null, and a crafted link with no state would otherwise pass null === null.
        if (!state || !expectedState || state !== expectedState) {
            result = { status: 'state_mismatch', message: 'Sign-in could not be verified. Try again.' };
        } else {
            try {
                localStorage.setItem(AUTH_KEY, JSON.stringify({
                    accessToken,
                    obtainedAt: Date.now(),
                    expiresAt: null
                }));
            } catch (e) {
                // Storage unavailable — nothing persisted, but still report 'ok' since
                // the token itself was validly received; restoreSession() will simply
                // find nothing to restore next load.
            }
            result = { status: 'ok' };
        }
    } else {
        const description = searchParams.get('error_description');
        result = {
            status: 'error',
            message: description
                ? `Sign-in didn't finish. ${description}`
                : "Sign-in didn't finish. Twitch sent no token. Try again."
        };
    }

    // Clean the URL: drop error/error_description/state, keep everything else, no hash.
    const cleanedParams = new URLSearchParams(loc.search || '');
    cleanedParams.delete('error');
    cleanedParams.delete('error_description');
    cleanedParams.delete('state');
    const qs = cleanedParams.toString();
    try {
        hist.replaceState(null, '', loc.pathname + (qs ? `?${qs}` : ''));
    } catch (e) {}

    return result;
}

export function getAccessToken() {
    try {
        const raw = localStorage.getItem(AUTH_KEY);
        if (!raw) return null;
        const parsed = JSON.parse(raw);
        return parsed?.accessToken || null;
    } catch (e) {
        return null;
    }
}

export function getAuthHeaders() {
    const token = getAccessToken();
    return token ? { Authorization: `Bearer ${token}` } : {};
}

export function getCachedUser() {
    try {
        const raw = localStorage.getItem(USER_KEY);
        if (!raw) return null;
        return JSON.parse(raw);
    } catch (e) {
        return null;
    }
}

export function clearSession() {
    try {
        localStorage.removeItem(AUTH_KEY);
        localStorage.removeItem(USER_KEY);
    } catch (e) {}
}

/**
 * Validate the stored token against Twitch and refresh the cached user.
 * Never logs the user out on a flaky network — only an explicit 401 or a
 * client_id mismatch (token belongs to a different app) clears the session.
 */
export async function restoreSession({ fetchImpl = fetch } = {}) {
    const token = getAccessToken();
    if (!token) return null;

    let res;
    try {
        res = await fetchImpl(VALIDATE_URL, {
            headers: { Authorization: `OAuth ${token}` }
        });
    } catch (e) {
        return getCachedUser();
    }

    if (res.status === 401) {
        clearSession();
        return null;
    }

    if (!res.ok) {
        return getCachedUser();
    }

    let data;
    try {
        data = await res.json();
    } catch (e) {
        return getCachedUser();
    }

    if (data.client_id !== TWITCH_CLIENT_ID) {
        clearSession();
        return null;
    }

    try {
        const raw = localStorage.getItem(AUTH_KEY);
        const auth = raw ? JSON.parse(raw) : { accessToken: token, obtainedAt: Date.now() };
        auth.expiresAt = Date.now() + (Number(data.expires_in) || 0) * 1000;
        localStorage.setItem(AUTH_KEY, JSON.stringify(auth));
    } catch (e) {}

    const cachedAt = Date.now();
    let user;
    try {
        const usersRes = await fetchImpl(USERS_URL, {
            headers: {
                Authorization: `Bearer ${token}`,
                'Client-Id': TWITCH_CLIENT_ID
            }
        });
        if (!usersRes.ok) throw new Error(`HTTP ${usersRes.status}`);
        const usersData = await usersRes.json();
        const u = usersData?.data?.[0];
        if (!u) throw new Error('No user data returned');
        user = {
            id: String(u.id),
            login: data.login,
            displayName: u.display_name || data.login,
            avatarUrl: u.profile_image_url || null,
            cachedAt
        };
    } catch (e) {
        user = {
            id: String(data.user_id),
            login: data.login,
            displayName: data.login,
            avatarUrl: null,
            cachedAt
        };
    }

    try {
        localStorage.setItem(USER_KEY, JSON.stringify(user));
    } catch (e) {}

    return user;
}

/**
 * Revoke the token with Twitch (best-effort — result/errors are ignored) and
 * always clear local session state. Never throws.
 */
export async function logout({ fetchImpl = fetch } = {}) {
    const token = getAccessToken();
    if (token) {
        try {
            await fetchImpl(REVOKE_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: new URLSearchParams({ client_id: TWITCH_CLIENT_ID, token }).toString()
            });
        } catch (e) {}
    }
    clearSession();
}
